/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionServiciosConsolas;

import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.ServicioTecnico;
import org.example.firebase;

import javax.swing.*;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 *
 * @author basty
 */
public class AgregarServicioConsola extends javax.swing.JPanel {
    private firebase firebaseInstance;
    private ServicioTecnico servicioTecnico;

    /**
     * Creates new form AgregarServicioConsola
     */
    public AgregarServicioConsola(firebase firebaseInstance) {
        this.servicioTecnico = InicioSesion.getServicioTecnico();
        this.firebaseInstance = firebaseInstance;
        initComponents();
    }

    public void AgregarServiciosParaConsolas(){
        String nombre = txtNombre.getText();
        String tiempoEstimado = txtTiempoEstimado.getText();
        String modeloDeConsola = txtModeloDeConsola.getText();
        String marcaConsola = txtMarcaConsola.getText();
        Optional<Double> valorServicio = parseDouble(txtValor.getText());

        List<String> errores = validarCampos(nombre, valorServicio, tiempoEstimado, modeloDeConsola, marcaConsola);

        if (!errores.isEmpty()) {
            String mensajeDeErrores = String.join("\n", errores);
            JOptionPane.showMessageDialog(this, mensajeDeErrores);
            return;
        }

        servicioTecnico.registrarServicioConsolas(nombre, valorServicio.get(), tiempoEstimado, modeloDeConsola, marcaConsola, firebaseInstance);
        JOptionPane.showMessageDialog(this, "Servicio de consola agregado correctamente");
    }

    private Optional<Double> parseDouble(String text) {
        try {
            return Optional.of(Double.parseDouble(text));
        } catch (NumberFormatException e) {
            return Optional.empty();
        }
    }

    private List<String> validarCampos(String nombre, Optional<Double> valorServicio, String tiempoestimado, String modeloDeConsola, String marcaConsola) {
        String mensaje = "Por favor, complete todos los campos";
        return Stream.of(
                        validarCampo(nombre, mensaje),
                        valorServicio.filter(v -> v > 0).map(v -> (String) null).orElse("Por favor, ingrese un valor numérico en el campo Valor"),
                        validarCampo(tiempoestimado, mensaje),
                        validarCampo(modeloDeConsola, mensaje),
                        validarCampo(marcaConsola, mensaje)
                )
                .filter(error -> error != null)
                .collect(Collectors.toList());
    }

    private String validarCampo(String campo, String mensajeError) {
        return campo.isEmpty() ? mensajeError : null;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTiempoEstimado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtModeloDeConsola = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMarcaConsola = new javax.swing.JTextField();
        btnAgregarServicioConsolas = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese los datos para su nuevo servicio para consolas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 30));

        jLabel3.setText("Valor");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, 30));

        jLabel4.setText("Detalle");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetalleActionPerformed(evt);
            }
        });
        add(txtDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 340, 170));

        jLabel5.setText("Tiempo estimado");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 30));

        txtTiempoEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoEstimadoActionPerformed(evt);
            }
        });
        add(txtTiempoEstimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 220, 30));

        jLabel6.setText("Modelo De La Consola");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        txtModeloDeConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloDeConsolaActionPerformed(evt);
            }
        });
        add(txtModeloDeConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 220, 30));

        jLabel7.setText("Marca Consola");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        txtMarcaConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaConsolaActionPerformed(evt);
            }
        });
        add(txtMarcaConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 220, 30));

        btnAgregarServicioConsolas.setText("Agregar Servicio");
        btnAgregarServicioConsolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioConsolasActionPerformed(evt);
            }
        });
        add(btnAgregarServicioConsolas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 120, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTiempoEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoEstimadoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetalleActionPerformed

    private void txtModeloDeConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloDeConsolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloDeConsolaActionPerformed

    private void txtMarcaConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaConsolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaConsolaActionPerformed

    private void btnAgregarServicioConsolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioConsolasActionPerformed
       AgregarServiciosParaConsolas();
    }//GEN-LAST:event_btnAgregarServicioConsolasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServicioConsolas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDetalle;
    private javax.swing.JTextField txtMarcaConsola;
    private javax.swing.JTextField txtModeloDeConsola;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTiempoEstimado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
