/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionServiciosConsolas;

/**
 *
 * @author basty
 */
public class EliminarServicioConsola extends javax.swing.JPanel {

    /**
     * Creates new form EliminarServicioConsola
     */
    public EliminarServicioConsola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreServicioConEliminar = new javax.swing.JTextField();
        btnEliminarServicio = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Aqui se eliminaran servicios consolas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel2.setText("Ingrese El nombre de el servicio de consolas que desee eliminar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        add(txtNombreServicioConEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 60));

        btnEliminarServicio.setText("Eliminar Servicio");
        add(btnEliminarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreServicioConEliminar;
    // End of variables declaration//GEN-END:variables
}
