/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionServiciosConsolas;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import org.example.firebase;

import javax.swing.*;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author basty
 */
public class EliminarServicioConsola extends javax.swing.JPanel {
    private firebase firebaseInstance;
    private ServiciosConsolas serviciosConsolas;

    /**
     * Creates new form EliminarServicioConsola
     */
    public EliminarServicioConsola(firebase firebaseInstance) {
        this.firebaseInstance = firebaseInstance;
        this.serviciosConsolas = new ServiciosConsolas(firebaseInstance);
        initComponents();
    }

    public void eliminarServicioConsolaConNombre(String nombre){
        try {
            Firestore db = firebaseInstance.getFirestore();
            CollectionReference collectionRef = db.collection("Registro de servicio consola");
            ApiFuture<QuerySnapshot> query = collectionRef.whereEqualTo("Nombre", nombre).get();
            QuerySnapshot querySnapshot = query.get();
            System.out.println("Consultando Servicios para consola con nombre : " + nombre);

            if (!querySnapshot.isEmpty()) {
                querySnapshot.getDocuments().stream()
                        .map(QueryDocumentSnapshot::getReference)
                        .forEach(documentRef -> {
                            try {
                                documentRef.delete().get();
                                System.out.println("Servicios consola con nombre  " + nombre + " eliminado de la Firebase");
                            } catch (InterruptedException | ExecutionException e) {
                                e.printStackTrace();
                                System.err.println("Error durante la operación: " + e.getMessage());
                            }
                        });
                JOptionPane.showMessageDialog(null, "Servicios consola con nombre" + nombre + " eliminado de la Firebase");
            } else {
                JOptionPane.showMessageDialog(null, "No hay Servicios consola con nombre " + nombre + " en la Firebase");
                System.out.println("No se encontró un producto con nombre " + nombre);
            }
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
            System.err.println("Error durante la operación: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreServicioConEliminar = new javax.swing.JTextField();
        btnEliminarServicio = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Aqui se eliminaran servicios consolas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel2.setText("Ingrese El nombre de el servicio de consolas que desee eliminar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        add(txtNombreServicioConEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 60));

        btnEliminarServicio.setText("Eliminar Servicio");
        btnEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarServicioActionPerformed(evt);
            }
        });
        add(btnEliminarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioActionPerformed
       String nombre = txtNombreServicioConEliminar.getText();
       if(nombre.isEmpty()){
           JOptionPane.showMessageDialog(null, "Debe ingresar un nombre de servicio de consola");
           return;
       }
       eliminarServicioConsolaConNombre(nombre);

    }//GEN-LAST:event_btnEliminarServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreServicioConEliminar;
    // End of variables declaration//GEN-END:variables
}
