/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionServiciosConsolas;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import org.example.Interfaces.PaginaPrincipal;
import org.example.ServicioTecnico;
import org.example.firebase;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author basty
 */
public class ServiciosConsolas extends javax.swing.JPanel {
    private firebase firebaseInstance;
    private DefaultTableModel modelotablaServicios;
    private ServicioTecnico servicioTecnico;


      private void MostrarPanelConsolas(JPanel pag ){
        
        pag.setSize(1500, 590);
        pag.setLocation(0,0);
        
        PanelServiciosConsolas.removeAll();
        PanelServiciosConsolas.add(pag, BorderLayout.CENTER);
        PanelServiciosConsolas.revalidate();
        PanelServiciosConsolas.repaint(); 
     }

    /**
     * Creates new form ServiciosConsolas
     */
    public ServiciosConsolas(firebase firebaseInstance) {
        this.servicioTecnico = PaginaPrincipal.getServicioTecnico();
        this.firebaseInstance = firebaseInstance;
        initComponents();
        AgregarServicioConsola menuconsolas = new AgregarServicioConsola(firebaseInstance);
        MostrarPanelConsolas(menuconsolas);
        cargarServiciosConsolasDesdeFirebase();
    }

    public void cargarServiciosConsolasDesdeFirebase(){
        modelotablaServicios = (DefaultTableModel) TablaServicioConsolas.getModel();
        modelotablaServicios.setRowCount(0);

        try{
            Firestore db = firebaseInstance.getFirestore();
            ApiFuture<QuerySnapshot> future = db.collection("Registro de servicio consola").get();
            QuerySnapshot querySnapshot = future.get();

            List<String[]> listaServicios = new ArrayList<>();

            for (QueryDocumentSnapshot documet : querySnapshot.getDocuments()) {
                String nombre = documet.getString("Nombre");
                double valorservicio = documet.getDouble("Valor");
                String tiempoestimado = documet.getString("TiempoEstimado");
                String tipoconsola = documet.getString("TipoConsola");
                String marcaconsola = documet.getString("MarcaConsola");

                listaServicios.add(new String[]{nombre, String.valueOf(valorservicio), tiempoestimado, tipoconsola, marcaconsola});
            }


            for(String[] servicio : listaServicios){
                modelotablaServicios.addRow(servicio);
            }
        }catch (Exception e){
            e.printStackTrace();
            System.out.println("Error al cargar datos"+ e.getMessage());
        }
    }

    public void refrescarTabla(){
        cargarServiciosConsolasDesdeFirebase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelServiciosConsolas = new javax.swing.JPanel();
        AgregarServicioConsola = new javax.swing.JButton();
        ModificarServicioConsola = new javax.swing.JButton();
        EliminarServicioConsola = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaServicioConsolas = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Aqui se mostraran los serfvicios para las comsolas ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 260, 20));

        javax.swing.GroupLayout PanelServiciosConsolasLayout = new javax.swing.GroupLayout(PanelServiciosConsolas);
        PanelServiciosConsolas.setLayout(PanelServiciosConsolasLayout);
        PanelServiciosConsolasLayout.setHorizontalGroup(
            PanelServiciosConsolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        PanelServiciosConsolasLayout.setVerticalGroup(
            PanelServiciosConsolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jPanel1.add(PanelServiciosConsolas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 590));

        AgregarServicioConsola.setText("Agregar Servicio  Consola");
        AgregarServicioConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarServicioConsolaActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarServicioConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 170, 40));

        ModificarServicioConsola.setText("Modificar Servicio consola");
        ModificarServicioConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarServicioConsolaActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarServicioConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, 170, 40));

        EliminarServicioConsola.setText("Eliminar Servicio Consola");
        EliminarServicioConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarServicioConsolaActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarServicioConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 170, 40));

        TablaServicioConsolas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Valor", "Tiempo Estimado", "Modelo Consola","Marca Consola"
            }
        ));
        jScrollPane1.setViewportView(TablaServicioConsolas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 300, 210));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarServicioConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarServicioConsolaActionPerformed
      AgregarServicioConsola menuconsolas = new AgregarServicioConsola(firebaseInstance);
        MostrarPanelConsolas(menuconsolas);
    }//GEN-LAST:event_AgregarServicioConsolaActionPerformed

    private void ModificarServicioConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarServicioConsolaActionPerformed
      ModificarServicioConsola modsercon = new ModificarServicioConsola();
      MostrarPanelConsolas(modsercon);
    }//GEN-LAST:event_ModificarServicioConsolaActionPerformed

    private void EliminarServicioConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarServicioConsolaActionPerformed
    EliminarServicioConsola elisercon = new EliminarServicioConsola();
    MostrarPanelConsolas(elisercon);
    }//GEN-LAST:event_EliminarServicioConsolaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarServicioConsola;
    private javax.swing.JButton EliminarServicioConsola;
    private javax.swing.JButton ModificarServicioConsola;
    private javax.swing.JPanel PanelServiciosConsolas;
    private javax.swing.JTable TablaServicioConsolas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
