/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces;

/**
 *
 * @author basty
 */
public class InicioMenu extends javax.swing.JPanel {

    /**
     * Creates new form InicioMenu
     */
    public InicioMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Bienvenido a su administrador de servicio tecnico");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 830, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("<html><center>Dentro de este sistema usted podra administrar sus diferentes servicios , Ingresar clientes y sobredodo adminsitrar sus ventras e ingresos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 540, 310));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("<html><center>Atravez de los siguientes menus usted podra acceder a los diferentes administradores ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 420, 100));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 590));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
