/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces;

/**
 *
 * @author basty
 */
public class InicioMenu extends javax.swing.JPanel {

    /**
     * Creates new form InicioMenu
     */
    public InicioMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel2.setText("Bienvenido a su administrador de servicio tecnico");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 830, 70));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel1.setText("desde aqui usted podrá manejar  las diferentes funcionalidades  que presenta nuestro negocio.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -80, 1220, 320));

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel3.setText("entre ellas está el manejo de gestión de clinetes, ventas, carrito de compras y productos");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -50, 1180, 330));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 590));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
