/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionServiciosPc;

import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.Interfaces.PaginaPrincipal;
import org.example.ServicioTecnico;
import org.example.firebase;


import javax.swing.*;

/**
 *
 * @author basty
 */
public class AgregarServiciosPc extends javax.swing.JPanel {
    private firebase firebaseInstance;
    private ServicioTecnico servicioTecnico;

    /**
     * Creates new form AgregarServiciosPc
     */
   public void AgregarServicioParaPc(){
       String nombre = txtNombre.getText();
       double valorServicio;

       // Desde aqui hacia abajo pueden colocar condiciones a los datos ingresados

       try {
           valorServicio = Double.parseDouble(txtValorServicioPc.getText());
       }catch (NumberFormatException ex){
           JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor numérico en el campo Valor");
           return;
       }

       String tiempoEstimado = txtTiempoEstimado.getText();
       String tipoDeComputadora = txtTipoDeComputador.getText();
       String lineaDeProcesador = txtLineaDeProcesador.getText();
       String usoDeComputadora = txtUsoDeComputadora.getText();

       if(nombre.isEmpty()|| tiempoEstimado.isEmpty()||tipoDeComputadora.isEmpty()||lineaDeProcesador.isEmpty()||usoDeComputadora.isEmpty()){
           JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos");
           return;
       }


       // Hasta aqui pueden agregar condiciones


       servicioTecnico.registrarServicioComputador(nombre,valorServicio,tiempoEstimado,tipoDeComputadora,lineaDeProcesador,usoDeComputadora,firebaseInstance);
       JOptionPane.showMessageDialog(this, "Servicio agregado correctamente");

       txtNombre.setText("");
       txtValorServicioPc.setText("");
       txtTiempoEstimado.setText("");
       txtTipoDeComputador.setText("");
       txtLineaDeProcesador.setText("");
       txtUsoDeComputadora.setText("");

   }



    public AgregarServiciosPc(firebase firebaseInstance){
       this.servicioTecnico = InicioSesion.getServicioTecnico();
       this.firebaseInstance = firebaseInstance;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValorServicioPc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDetalleServicioPc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTiempoEstimado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTipoDeComputador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUsoDeComputadora = new javax.swing.JTextField();
        btnAgregarServiciosPc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtLineaDeProcesador = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese su nuevo servicio para pc");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 30));

        jLabel3.setText("Valor Servicio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtValorServicioPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorServicioPcActionPerformed(evt);
            }
        });
        add(txtValorServicioPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 30));

        jLabel4.setText("Detalle Servicio");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtDetalleServicioPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetalleServicioPcActionPerformed(evt);
            }
        });
        add(txtDetalleServicioPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 380, 140));

        jLabel5.setText("Tiempo Estimado");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtTiempoEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoEstimadoActionPerformed(evt);
            }
        });
        add(txtTiempoEstimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 30));

        jLabel6.setText("Tipo De Computador");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        txtTipoDeComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoDeComputadorActionPerformed(evt);
            }
        });
        add(txtTipoDeComputador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 230, 30));

        jLabel7.setText("Uso de Computadora");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        txtUsoDeComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsoDeComputadoraActionPerformed(evt);
            }
        });
        add(txtUsoDeComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 230, 30));

        btnAgregarServiciosPc.setText("Agregar Servicio Pc");
        btnAgregarServiciosPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServiciosPcActionPerformed(evt);
            }
        });
        add(btnAgregarServiciosPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 150, 40));

        jLabel8.setText("Linea De Procesador");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 130, 20));
        add(txtLineaDeProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsoDeComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsoDeComputadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsoDeComputadoraActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtValorServicioPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorServicioPcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorServicioPcActionPerformed

    private void txtDetalleServicioPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetalleServicioPcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetalleServicioPcActionPerformed

    private void txtTiempoEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoEstimadoActionPerformed

    private void txtTipoDeComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoDeComputadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoDeComputadorActionPerformed

    private void btnAgregarServiciosPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServiciosPcActionPerformed
        AgregarServicioParaPc();
    }//GEN-LAST:event_btnAgregarServiciosPcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServiciosPc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDetalleServicioPc;
    private javax.swing.JTextField txtLineaDeProcesador;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTiempoEstimado;
    private javax.swing.JTextField txtTipoDeComputador;
    private javax.swing.JTextField txtUsoDeComputadora;
    private javax.swing.JTextField txtValorServicioPc;
    // End of variables declaration//GEN-END:variables
}
