/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionServiciosPc;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import org.example.firebase;
import javax.swing.*;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author basty
 */
public class EliminarServiciosPc extends javax.swing.JPanel {
    private firebase firebaseInstance;

    /**
     * Creates new form EliminarServiciosPc
     */
    public EliminarServiciosPc(firebase firebaseInstance) {
        this.firebaseInstance = firebaseInstance;

        initComponents();
    }

    public void eliminarServicioPcConNombre(String nombre){
        Firestore db = firebaseInstance.getFirestore();
        CollectionReference collectionRef = db.collection("Registro de servicio computador");
        
        try {
            ApiFuture<QuerySnapshot> query = collectionRef.whereEqualTo("Nombre", nombre).get();
            QuerySnapshot querySnapshot = query.get();
            System.out.println("Consultando Servicios para Pc con nombre : " + nombre);

            if (!querySnapshot.isEmpty()) {
                querySnapshot.getDocuments().stream()
                        .map(QueryDocumentSnapshot::getReference)
                        .forEach(documentRef -> {
                            try {
                                documentRef.delete().get();
                                System.out.println("Servicios Pc con nombre  " + nombre + " eliminado de la Firebase");
                            } catch (InterruptedException | ExecutionException e) {
                                e.printStackTrace();
                                System.err.println("Error durante la operación: " + e.getMessage());
                            }
                        });
                JOptionPane.showMessageDialog(null, "Servicios Pc con nombre" + nombre + " eliminado de la Firebase");
                JOptionPane.showMessageDialog(null, "Para recargar la tabla presione el boton (Servicios Pc)");
            } else {
                JOptionPane.showMessageDialog(null, "No hay Servicios Pc con nombre " + nombre + " en la Firebase");
                System.out.println("No se encontró un servicio con nombre " + nombre);
            }
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
            System.err.println("Error durante la operación: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreServicioPcEliminar = new javax.swing.JTextField();
        btnEliminarServicioPc = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Eliminador de servicios pc");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setText("Nombre Del Servicio De Computador Que Desee Eliminar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtNombreServicioPcEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreServicioPcEliminarActionPerformed(evt);
            }
        });
        add(txtNombreServicioPcEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 360, 60));

        btnEliminarServicioPc.setText("Eliminar Servicio");
        btnEliminarServicioPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarServicioPcActionPerformed(evt);
            }
        });
        add(btnEliminarServicioPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreServicioPcEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreServicioPcEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreServicioPcEliminarActionPerformed

    private void btnEliminarServicioPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioPcActionPerformed
        String nombre = txtNombreServicioPcEliminar.getText();
eliminarServicioPcConNombre(nombre);
    }//GEN-LAST:event_btnEliminarServicioPcActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarServicioPc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreServicioPcEliminar;
    // End of variables declaration//GEN-END:variables
}
