/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionServiciosPc;

/**
 *
 * @author basty
 */
public class EliminarServiciosPc extends javax.swing.JPanel {

    /**
     * Creates new form EliminarServiciosPc
     */
    public EliminarServiciosPc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreServicioPcEliminar = new javax.swing.JTextField();
        btnEliminarServicioPc = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Eliminador de servicios pc");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setText("Nombre Del Servicio De Computador Que Desee Eliminar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtNombreServicioPcEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreServicioPcEliminarActionPerformed(evt);
            }
        });
        add(txtNombreServicioPcEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 360, 60));

        btnEliminarServicioPc.setText("Eliminar Servicio");
        add(btnEliminarServicioPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreServicioPcEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreServicioPcEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreServicioPcEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarServicioPc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreServicioPcEliminar;
    // End of variables declaration//GEN-END:variables
}
