/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionServiciosPc;

import org.example.firebase;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author basty
 */
public class ServiciosPc extends javax.swing.JPanel {
    private firebase firebaseInstance;



      private void MostrarPanelServiciosPc(JPanel pag ){
        
        pag.setSize(1500, 590);
        pag.setLocation(0,0);
        
        PanelServiciosPc.removeAll();
        PanelServiciosPc.add(pag, BorderLayout.CENTER);
        PanelServiciosPc.revalidate();
        PanelServiciosPc.repaint(); 
     }

    /**
     * Creates new form ServiciosPc
     */
    public ServiciosPc(firebase firebaseInstance) {
        this.firebaseInstance = firebaseInstance;
        initComponents();
        AgregarServiciosPc agrserpc = new AgregarServiciosPc();
        MostrarPanelServiciosPc(agrserpc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelServiciosPc = new javax.swing.JPanel();
        BotonAgregarServicioPc = new javax.swing.JButton();
        BotonEliminarServicio = new javax.swing.JButton();
        BotonModificarServicioPc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaServiciosPC = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(810, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Aqui se mostraran los servicios para pc");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 277, 82));

        javax.swing.GroupLayout PanelServiciosPcLayout = new javax.swing.GroupLayout(PanelServiciosPc);
        PanelServiciosPc.setLayout(PanelServiciosPcLayout);
        PanelServiciosPcLayout.setHorizontalGroup(
            PanelServiciosPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        PanelServiciosPcLayout.setVerticalGroup(
            PanelServiciosPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jPanel1.add(PanelServiciosPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 590));

        BotonAgregarServicioPc.setText("Agregar Servicio Pc");
        BotonAgregarServicioPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarServicioPcActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAgregarServicioPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 160, 30));

        BotonEliminarServicio.setText("Eliminar Servicio Pc");
        BotonEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarServicioActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 140, 30));

        BotonModificarServicioPc.setText("Modificar Servicio Pc");
        BotonModificarServicioPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarServicioPcActionPerformed(evt);
            }
        });
        jPanel1.add(BotonModificarServicioPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 160, 30));

        TablaServiciosPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaServiciosPC);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 460, 250));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarServicioPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarServicioPcActionPerformed
       AgregarServiciosPc agrserpc = new AgregarServiciosPc();
        MostrarPanelServiciosPc(agrserpc);
    }//GEN-LAST:event_BotonAgregarServicioPcActionPerformed

    private void BotonEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarServicioActionPerformed
      EliminarServiciosPc eliserpc = new EliminarServiciosPc();
      MostrarPanelServiciosPc(eliserpc);
    }//GEN-LAST:event_BotonEliminarServicioActionPerformed

    private void BotonModificarServicioPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarServicioPcActionPerformed
        ModificarServiciosPc modserpc = new ModificarServiciosPc();
        MostrarPanelServiciosPc(modserpc);
    }//GEN-LAST:event_BotonModificarServicioPcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarServicioPc;
    private javax.swing.JButton BotonEliminarServicio;
    private javax.swing.JButton BotonModificarServicioPc;
    private javax.swing.JPanel PanelServiciosPc;
    private javax.swing.JTable TablaServiciosPC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
