/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionVentas;

import org.example.ServicioTecnico;
import org.example.Venta;

import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author basty
 */
public class VentasServicio extends javax.swing.JPanel {

    private ServicioTecnico servicioTecnico;

    /**
     * Creates new form VentasServicio
     */
    public VentasServicio(ServicioTecnico servicioTecnico) {
        this.servicioTecnico = servicioTecnico;
        initComponents();
        cargarVentasLocalesServicioTecnico();
    }

    public void cargarVentasLocalesServicioTecnico(){
        List<Venta> listaVentas = servicioTecnico.getListaVentas();

        DefaultTableModel modeloTablaVentas = (DefaultTableModel) TablaVentasServicio.getModel();
        modeloTablaVentas.setRowCount(0);

        listaVentas.forEach(venta -> {
            Object[] rowData = {
                    venta.getFechaVenta(),
                    venta.getIva(),
                    venta.getTotal()
            };
            modeloTablaVentas.addRow(rowData);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVentasServicio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaVentasServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha De Venta", "IVA", "Total De Venta"
            }
        ));
        jScrollPane1.setViewportView(TablaVentasServicio);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 880, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ventas Totales de Su Servicio Tecnico");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 340, 30));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html><center>Dentro de este campo usted podra ver las ventas totales de su servicio tecnico lo cual le mostrara la fecha en la cual se hizo cada venta , su total y su iva respectivamente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 320, 310));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 590));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaVentasServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
