/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionVentas;

import org.example.ServicioTecnico;
import org.example.Venta;

import java.util.List;

/**
 *
 * @author basty
 */
public class VentasServicio extends javax.swing.JPanel {

    private ServicioTecnico servicioTecnico;

    /**
     * Creates new form VentasServicio
     */
    public VentasServicio(ServicioTecnico servicioTecnico) {
        this.servicioTecnico = servicioTecnico;
        initComponents();
        cargarVentasLocalesServicioTecnico();
    }

    public void cargarVentasLocalesServicioTecnico(){
        List<Venta> listaVentas = servicioTecnico.getListaVentas();

        String[] columnas = {"FechaVenta","iva","Total"};
        Object[][] data = new Object[listaVentas.size()][columnas.length];

        for(int i = 0; i < listaVentas.size(); i++){
            Venta venta = listaVentas.get(i);
            data[i][0] = venta.getFechaVenta();
            data[i][1] = venta.getIva();
            data[i][2] = venta.getTotal();
        }

        TablaVentasServicio.setModel(new javax.swing.table.DefaultTableModel(data, columnas));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVentasServicio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaVentasServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaVentasServicio);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 590, 450));

        jLabel1.setText("Aqui se mostrara la lista de ventas de el servicio");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaVentasServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
