/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Interfaces.InterfazDeCliente;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import org.example.Cliente;
import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.ServicioTecnico;
import org.example.Venta;
import org.example.firebase;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author basty
 */
public class InterfazParaElCliente extends javax.swing.JFrame {
    private ServicioTecnico servicioTecnico;
    private firebase firebaseInstance;

    /**
     * Creates new form InterfazParaElCliente
     */
    public InterfazParaElCliente(firebase firebaseInstance) {
        this.firebaseInstance = firebaseInstance;
        this.servicioTecnico = InicioSesion.getServicioTecnico();
        firebaseInstance.inicializarconexion();
        initComponents();
    }

    private void cargarClientesDesdeFirebase(){


        List<Cliente> listaClientesLocal = new ArrayList<>();
        StringBuilder clientesConVentas = new StringBuilder();

        try{
            Firestore db = firebaseInstance.getFirestore();
            ApiFuture<QuerySnapshot> future = db.collection("Registro De Clientes").get();
            QuerySnapshot querySnapshot = future.get();


            for (QueryDocumentSnapshot document : querySnapshot.getDocuments()) {
                String nombre = document.getString("Nombre");
                String apellido = document.getString("Apellido");
                String telefono = document.getString("Telefono");
                String email = document.getString("Email");
                String rut = document.getString("Rut");
                String region = document.getString("Region");
                String comuna = document.getString("Comuna");

                Cliente cliente = new Cliente(nombre,
                        apellido,
                        telefono,
                        email,
                        rut,
                        region,
                        comuna);
                listaClientesLocal.add(cliente);



                ApiFuture<QuerySnapshot> futureVentas = db.collection("Registro De Ventas").whereEqualTo("Rut Cliente", rut).get();
                QuerySnapshot querySnapshotVentas = futureVentas.get();

                List<Venta> listaVentasCliente = new ArrayList<>();
                for (QueryDocumentSnapshot documentVenta : querySnapshotVentas.getDocuments()) {
                    String fechaVenta = documentVenta.getString("Fecha De Venta");
                    String totalVenta = documentVenta.getString("Total Venta");
                    String ivaVenta = documentVenta.getString("IVA Impuesto");

                    Venta venta = new Venta(fechaVenta, ivaVenta,totalVenta);
                    listaVentasCliente.add(venta);
                }

                cliente.setVentascliente(listaVentasCliente);

                clientesConVentas.append("Cliente: ").append(cliente.getNombre()).append(" ").append(cliente.getApellido()).append("\n");
                clientesConVentas.append("Ventas: \n");
                for (Venta venta : listaVentasCliente) {
                    clientesConVentas.append("- Fecha: ").append(venta.getFechaVenta()).append(", Total: ").append(venta.getTotal()).append("\n");
                }
                clientesConVentas.append("\n");
            }

            servicioTecnico.setListaClientes(listaClientesLocal);

            System.out.println("Clientes existentes");

            //debug
            listaClientesLocal.stream().forEach(System.out::println);
            for (Cliente cliente : listaClientesLocal){
                System.out.println(cliente);
            }

            System.out.println("\nClientes con ventas:");
            System.out.println(clientesConVentas.toString());

        }catch (Exception e){
            e.printStackTrace();
            System.out.println("Error al cargar datos"+ e.getMessage());
        }
    }


    public firebase getFirebaseInstance(){
        return firebaseInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRutCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Esta sera la interfaz del cliente ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 310, 40));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Reingrese su rut para obtener sus datos porfavor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(txtRutCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 540));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "item 6 ", "item 7 ", "item 8 ", "item 9", "item 10", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 380, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazParaElCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazParaElCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazParaElCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazParaElCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                firebase firebaseInstance = new firebase();
                new InterfazParaElCliente(firebaseInstance).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtRutCliente;
    // End of variables declaration//GEN-END:variables
}
