/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.InterfazDeCliente;

import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.Producto;
import org.example.ServicioTecnico;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author basty
 */
public class ProductosCliente extends javax.swing.JPanel {
    private ServicioTecnico servicioTecnico;

    /**
     * Creates new form ProductosCliente
     */
    public ProductosCliente() {
        initComponents();
       this.servicioTecnico = InicioSesion.getServicioTecnico();
       cargarProductosATabla();

    }

    private void cargarProductosATabla(){
        DefaultTableModel model = (DefaultTableModel) TablaProductosCliente.getModel();
        model.setRowCount(0);
    
        List<Producto> productos = servicioTecnico.getProductos().stream().collect(Collectors.toList());
    
        productos.stream()
                .map(producto -> new Object[]{producto.getNombreProducto(),
                        producto.getCategoriaProducto(),
                        producto.getValorProducto(),
                        producto.getStockProducto()})
                .forEach(fila -> model.addRow(fila));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductosCliente = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(1100, 420));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Productos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        TablaProductosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Valor", "Stock"
            }
        ));
        jScrollPane1.setViewportView(TablaProductosCliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 550, 340));

        jLabel2.setText("<html><center>Aqi puede ver todos los productos disponibles dentro de el servicio tecnico");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 200));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductosCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
