/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.InterfazDeCliente;

import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.Producto;
import org.example.ServicioTecnico;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author basty
 */
public class ProductosCliente extends javax.swing.JPanel {
    private ServicioTecnico servicioTecnico;

    /**
     * Creates new form ProductosCliente
     */
    public ProductosCliente() {
        initComponents();
       this.servicioTecnico = InicioSesion.getServicioTecnico();
       cargarProductosATabla();

    }

    private void cargarProductosATabla(){

        DefaultTableModel model = (DefaultTableModel) TablaProductosCliente.getModel();
        model.setRowCount(0);

        for(Producto producto : servicioTecnico.getProductos()){
            Object[] fila = {producto.getNombreProducto(), producto.getCategoriaProducto(), producto.getValorProducto(), producto.getStockProducto()};
            model.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductosCliente = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Productos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        TablaProductosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProductosCliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 550, 340));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductosCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
