/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.InterfazDeCliente;

import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.ServicioConsolas;
import org.example.ServicioTecnico;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 *
 * @author basty
 */
public class ServiciosParaConsolasCliente extends javax.swing.JPanel {
    private ServicioTecnico servicioTecnico;

    /**
     * Creates new form ServiciosParaConsolasCliente
     */
    public ServiciosParaConsolasCliente() {
        initComponents();
        this.servicioTecnico = InicioSesion.getServicioTecnico();
        cargarServiciosConsolasATabla();
    }

    private void cargarServiciosConsolasATabla() {
        DefaultTableModel modeloTablaServicioConsolas = (DefaultTableModel) TablaServicioConsolasClientes.getModel();
        modeloTablaServicioConsolas.setRowCount(0);

        Collection<ServicioConsolas> servicioConsolasCol = servicioTecnico.getServiciosConsola();
        List<ServicioConsolas> servicioConsolas = new ArrayList<>(servicioConsolasCol);

        servicioConsolas.stream()
                .map(servicio -> new Object[]{
                        servicio.getNombre(),
                        servicio.getTiempoEstimado(),
                        servicio.getValorServicio(),
                        servicio.getModeloConsola(),
                        servicio.getMarcaConsola()
                })
                .forEach(modeloTablaServicioConsolas :: addRow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaServicioConsolasClientes = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(" Aqui iran los servicios consolas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 200, 30));

        TablaServicioConsolasClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tiempo Estimado", "Valor Servicio", "Modelo Consola","Marca consola"
            }
        ));
        jScrollPane1.setViewportView(TablaServicioConsolasClientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 510, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaServicioConsolasClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
