/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Interfaces.InicioSesion;
<<<<<<< HEAD
import org.example.Main;
import org.example.Servicio;
import org.example.ServicioTecnico;
import org.example.firebase;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

public class IncioDeSesion extends JFrame {
    ServicioTecnico s1 = new ServicioTecnico();
=======

/**
 *
 * @author basty
 */
public class IncioDeSesion extends javax.swing.JFrame {

    /**
     * Creates new form IncioDeSesion
     */
>>>>>>> parent of e8e0acb (feat: avance implementacion de firebase)
    public IncioDeSesion() {
        firebase f1 = new firebase();
        f1.inicializarconexion();
        s1.RegistrarCliente("juanito","perez","labranza");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        CasillaContraseña = new JTextField();
        jLabel4 = new JLabel();
        CasillaNombreUsuario = new JTextField();
        BotonIniciarSesion = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        Background.setLayout(new AbsoluteLayout());

        jLabel1.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Logo");
        Background.add(jLabel1, new AbsoluteConstraints(110, 60, 90, 50));

        jLabel2.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Iniciar Sesion");
        Background.add(jLabel2, new AbsoluteConstraints(110, 140, 140, 40));

        jLabel3.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        Background.add(jLabel3, new AbsoluteConstraints(110, 280, 80, 20));

        CasillaContraseña.setBorder(null);
        CasillaContraseña.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                CasillaContraseñaActionPerformed(evt);
            }
        });
        Background.add(CasillaContraseña, new AbsoluteConstraints(110, 320, 380, 30));

        jLabel4.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese su Nombre");
        Background.add(jLabel4, new AbsoluteConstraints(110, 190, 190, 30));

        CasillaNombreUsuario.setBorder(null);
        CasillaNombreUsuario.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                CasillaNombreUsuarioActionPerformed(evt);
            }
        });
        Background.add(CasillaNombreUsuario, new AbsoluteConstraints(110, 220, 380, 30));

        BotonIniciarSesion.setText("Iniciar Sesion");
        BotonIniciarSesion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                BotonIniciarSesionActionPerformed(evt);
            }
        });
        Background.add(BotonIniciarSesion, new AbsoluteConstraints(240, 400, 150, 60));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, GroupLayout.PREFERRED_SIZE, 841, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, GroupLayout.PREFERRED_SIZE, 538, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
<<<<<<< HEAD
    }
    private void CasillaContraseñaActionPerformed(ActionEvent evt) {

    }
    private void CasillaNombreUsuarioActionPerformed(ActionEvent evt) {

    }
    private void BotonIniciarSesionActionPerformed(ActionEvent evt) {
=======
    }// </editor-fold>//GEN-END:initComponents

    private void CasillaContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaContraseñaActionPerformed

    private void CasillaNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaNombreUsuarioActionPerformed
>>>>>>> parent of e8e0acb (feat: avance implementacion de firebase)

    private void BotonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IncioDeSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(IncioDeSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(IncioDeSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(IncioDeSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

<<<<<<< HEAD
        EventQueue.invokeLater(new Runnable() {
=======
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
>>>>>>> parent of e8e0acb (feat: avance implementacion de firebase)
            public void run() {
                new IncioDeSesion().setVisible(true);
            }
        });
    }

<<<<<<< HEAD
    private JPanel Background;
    private JButton BotonIniciarSesion;
    private JTextField CasillaContraseña;
    private JTextField CasillaNombreUsuario;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;

=======
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton BotonIniciarSesion;
    private javax.swing.JTextField CasillaContraseña;
    private javax.swing.JTextField CasillaNombreUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
>>>>>>> parent of e8e0acb (feat: avance implementacion de firebase)
}
