/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Interfaces.InicioSesion;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.*;
import org.example.Cliente;
import org.example.Interfaces.InterfazDeCliente.InterfazParaElCliente;
import org.example.Interfaces.PaginaPrincipal;
import org.example.ServicioTecnico;
import org.example.firebase;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author basty
 */
public class InicioSesion extends JFrame {

    private  firebase firebaseInstance;
    private static ServicioTecnico servicioTecnico;

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        servicioTecnico = new ServicioTecnico("Mi Servicio",null,null,null,null,null);
        this.firebaseInstance = new firebase();
        firebaseInstance.inicializarconexion();
        initComponents();

    }

    private void iniciarSesion() {
        String rutIngresado = txtIngresoDeRut.getText();
        System.out.println("RUT ingresado: " + rutIngresado);

        CollectionReference clientesCollection = firebaseInstance.getFirestore().collection("Registro De Clientes");
        ApiFuture<QuerySnapshot> querySnapshot = clientesCollection.get();

        try {
            List<QueryDocumentSnapshot> documents = querySnapshot.get().getDocuments();
            for (QueryDocumentSnapshot document : documents) {
                Map<String, Object> clienteData = document.getData();
                String rutCliente = (String) clienteData.get("Rut");

                if (rutCliente.equals(rutIngresado)) {
                    System.out.println("Cliente encontrado: " + clienteData);
                    InterfazParaElCliente interfazCliente = new InterfazParaElCliente(firebaseInstance);
                    interfazCliente.setVisible(true);
                    dispose();
                    return;
                }
            }

            JOptionPane.showMessageDialog(null, "El RUT De cliente no existe");
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }

        CollectionReference administradoresCollection = firebaseInstance.getFirestore().collection("Administradores");
        ApiFuture<QuerySnapshot> querySnapshotAdministradores = administradoresCollection.get();

        try{
            List<QueryDocumentSnapshot> documentsAdministradores = querySnapshotAdministradores.get().getDocuments();
            for (QueryDocumentSnapshot document : documentsAdministradores){
                Map<String, Object> administradorData = document.getData();
                String rutAdministrador = (String) administradorData.get("Rut");

                if(rutAdministrador.equals(rutIngresado)){
                    System.out.println("Administrador encontrado: " + administradorData);
                    PaginaPrincipal interfazPaginaPrincipal = new PaginaPrincipal(firebaseInstance);
                    interfazPaginaPrincipal.setVisible(true);
                    dispose();
                    return;
                }
            }
            JOptionPane.showMessageDialog(null, "El RUT no existe");
        }catch (InterruptedException | ExecutionException e){
            e.printStackTrace();
            System.err.println("Error durante la operacion"+e.getMessage());
        }
    }

    public static ServicioTecnico getServicioTecnico(){
        return servicioTecnico;
    }








    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        txtNombreDeUsuario = new JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jTextField2 = new JTextField();
        jLabel4 = new JLabel();
        txtIngresoDeRut = new JTextField();
        btnIngresar = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());

        jLabel1.setText("Logo empresa");
        getContentPane().add(jLabel1, new AbsoluteConstraints(130, 30, 140, 40));

        txtNombreDeUsuario.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtNombreDeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreDeUsuario, new AbsoluteConstraints(80, 170, 230, 30));

        jLabel2.setText("Ingrese su nombre de usuario");
        getContentPane().add(jLabel2, new AbsoluteConstraints(80, 140, 160, 30));

        jLabel3.setText("Ingrese contraseña");
        getContentPane().add(jLabel3, new AbsoluteConstraints(80, 300, -1, -1));
        getContentPane().add(jTextField2, new AbsoluteConstraints(80, 330, 230, 30));

        jLabel4.setText("Ingrese Su Rut");
        getContentPane().add(jLabel4, new AbsoluteConstraints(80, 210, -1, -1));

        txtIngresoDeRut.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtIngresoDeRutActionPerformed(evt);
            }
        });
        getContentPane().add(txtIngresoDeRut, new AbsoluteConstraints(80, 240, 230, 30));

        btnIngresar.setText("Iniciar Sesion");
        btnIngresar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new AbsoluteConstraints(170, 390, 220, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDeUsuarioActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtNombreDeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDeUsuarioActionPerformed

    private void btnIngresarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
      iniciarSesion();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtIngresoDeRutActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtIngresoDeRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresoDeRutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnIngresar;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JTextField jTextField2;
    private JTextField txtIngresoDeRut;
    private JTextField txtNombreDeUsuario;
    // End of variables declaration//GEN-END:variables
}
