/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionProductos;

import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.ServicioTecnico;
import org.example.firebase;
import javax.swing.*;
import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;

/**
 *
 * @author basty
 */
public class AgregarProductos extends javax.swing.JPanel {
    private firebase firebaseInstance;
    private Productos vistaProductos;
    private ServicioTecnico servicioTecnico;

    /**
     * Creates new form AgregarProductos
     */
    public AgregarProductos(firebase firebaseInstance,Productos vistaProductos) {
        this.firebaseInstance = firebaseInstance;
        this.servicioTecnico = InicioSesion.getServicioTecnico();
        this.vistaProductos = vistaProductos;
        initComponents();
    }

    public AgregarProductos() {
    }

    public void agregarNuevoProducto() {
        String nombre = txtNombre.getText().trim();
        String categoria = txtCategoria.getText().trim();

        try {
            double valor = parsearDouble(txtValor.getText().trim(), "Valor");
            int stock = Integer.parseInt(txtStock.getText().trim());

            validarCampos(nombre, categoria, valor, stock);

            servicioTecnico.registrarProducto(nombre, categoria, valor, stock, firebaseInstance);
            JOptionPane.showMessageDialog(null, "Producto registrado correctamente");

            limpiarCampos();

            vistaProductos.refrescarTablaProductos();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public double parsearDouble(String texto, String campo){
        try {
            return Double.parseDouble(texto);
        } catch (NumberFormatException e){
            throw new IllegalArgumentException("Por favor, ingrese un valor numérico válido en el campo " + campo);
        }
    }

    public void validarCampos(String nombre, String categoria, double valor, double stock) {
        List<Supplier<Optional<String>>> validaciones = List.of(
                () -> validarTexto(nombre, "Nombre", true),
                () -> validarTexto(categoria, "Categoría", true),
                () -> validarNumero(valor, "El Valor debe ser mayor a cero"),
                () -> validarNumero(stock, "El Stock debe ser mayor a cero")
        );

        validaciones.stream()
                .map(Supplier::get)
                .filter(Optional::isPresent)
                .findFirst()
                .ifPresent(error -> {
                    throw new IllegalArgumentException(error.get());
                });
    }

    public Optional<String> validarTexto(String texto, String mensajeError, boolean soloLetras) {
        if (texto == null || texto.trim().isEmpty()) {
            return Optional.of(mensajeError);
        }

        if (soloLetras && !texto.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ]+[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ ]*")) {
            return Optional.of("El texto solo puede contener letras en el campo: " + mensajeError);
        }
        return Optional.empty();
    }

    public Optional<String> validarNumero(double valor, String mensajeError) {
        return valor <= 0 ? Optional.of(mensajeError) : Optional.empty();
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtCategoria.setText("");
        txtValor.setText("");
        txtStock.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese Los Datos De Su Nuevo Producto");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoria");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 10));

        jLabel5.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stock");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 290, 30));

        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 290, 30));

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 290, 30));

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 30));

        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 150, 50));
    }// </editor-fold>//GEN-END:initComponents



    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        agregarNuevoProducto();
        vistaProductos.refrescarTablaProductos();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
