/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionProductos;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.Interfaces.PaginaPrincipal;
import org.example.Producto;
import org.example.ServicioTecnico;
import org.example.firebase;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author basty
 */
public class Productos extends javax.swing.JPanel {

    private firebase firebaseInstance;
    private DefaultTableModel modeloTablaProductos;
    private ServicioTecnico servicioTecnico;

      private void MostrarPanelProducto(JPanel pag ){
        
        pag.setSize(1500, 590);
        pag.setLocation(0,0);
        
        PanelProductos.removeAll();
        PanelProductos.add(pag, BorderLayout.CENTER);
        PanelProductos.revalidate();
        PanelProductos.repaint(); 
     }

     private void cargarProductosDesdeFirebase() {
         modeloTablaProductos = (DefaultTableModel) TablaProductos.getModel();
         modeloTablaProductos.setRowCount(0);

         List<Producto> listaProductosLocal = new ArrayList<>();

         try {
             Firestore db = firebaseInstance.getFirestore();
             ApiFuture<QuerySnapshot> future = db.collection("Registro de Producto").get();
             QuerySnapshot querySnapshot = future.get();

             querySnapshot.getDocuments().stream()
                     .map(document -> new Producto(
                             document.getString("Nombre"),
                             document.getString("Categoria"),
                             document.getDouble("Valor"),
                             document.getLong("Stock").intValue()
                     ))
                     .peek(producto -> listaProductosLocal.add(producto))
                     .forEach(producto -> modeloTablaProductos.addRow(new Object[]{
                             producto.getNombreProducto(),
                             producto.getCategoriaProducto(),
                             producto.getValorProducto(),
                             producto.getStockProducto()
                     }));

             servicioTecnico.setListaProductos(listaProductosLocal);

             System.out.println("Productos existentes");
             servicioTecnico.getProductos().stream()
                     .forEach(System.out ::println);

         } catch (Exception e) {
             e.printStackTrace();
             System.out.println("Error al cargar datos" + e.getMessage());
         }
     }

     public void refrescarTablaProductos(){
          cargarProductosDesdeFirebase();
     }

    /**
     * Creates new form Producto
     */
    public Productos(firebase firebaseInstance) {
        this.firebaseInstance = firebaseInstance;
        this.servicioTecnico = InicioSesion.getServicioTecnico();
        initComponents();
        cargarProductosDesdeFirebase();
        AgregarProductos menuproductos = new AgregarProductos(firebaseInstance,this);
        MostrarPanelProducto(menuproductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonAgregarProducto = new javax.swing.JButton();
        BotonEliminarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelProductos.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout PanelProductosLayout = new javax.swing.GroupLayout(PanelProductos);
        PanelProductos.setLayout(PanelProductosLayout);
        PanelProductosLayout.setHorizontalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        PanelProductosLayout.setVerticalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        add(PanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 590));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel1.setText("Productos ingresados : En esta tabla se mostraran todos los productos que usted registre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, 20));

        BotonAgregarProducto.setBackground(new java.awt.Color(204, 204, 255));
        BotonAgregarProducto.setFont(new java.awt.Font("Stencil", 1, 13)); // NOI18N
        BotonAgregarProducto.setText("AgregarProducto");
        BotonAgregarProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarProductoActionPerformed(evt);
            }
        });
        add(BotonAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 170, 50));

        BotonEliminarProducto.setBackground(new java.awt.Color(204, 204, 255));
        BotonEliminarProducto.setFont(new java.awt.Font("Stencil", 1, 13)); // NOI18N
        BotonEliminarProducto.setText("EliminarProducto");
        BotonEliminarProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarProductoActionPerformed(evt);
            }
        });
        add(BotonEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, 180, 50));

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Valor", "Stock"
            }
        ));
        jScrollPane1.setViewportView(TablaProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 670, 330));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel2.setText("y a medida que se ingresen, a su vez se actualizará la tabla en tiempo real");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarProductoActionPerformed
        AgregarProductos agrprod = new AgregarProductos(firebaseInstance,this);
               MostrarPanelProducto(agrprod);
    }//GEN-LAST:event_BotonAgregarProductoActionPerformed

    private void BotonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarProductoActionPerformed
        EliminarProductos eliprod = new EliminarProductos(firebaseInstance);
        MostrarPanelProducto(eliprod);
    }//GEN-LAST:event_BotonEliminarProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarProducto;
    private javax.swing.JButton BotonEliminarProducto;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
