package org.example.Interfaces.AdministracionClientes;
import org.example.Cliente;
import org.example.Interfaces.InicioSesion.InicioSesion;
import org.example.ServicioTecnico;
import org.example.firebase;
import java.awt.BorderLayout;
import java.util.List;
import java.util.Optional;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author basty
 */
public class Clientes extends javax.swing.JPanel {
    private firebase firebaseInstance;
    private ServicioTecnico servicioTecnico;
     private void MostrarPanelCliente(JPanel pag ){
        
        pag.setSize(1500, 590);
        pag.setLocation(0,0);
        
        PanelCliente.removeAll();
        PanelCliente.add(pag, BorderLayout.CENTER);
        PanelCliente.revalidate();
        PanelCliente.repaint(); 
     }

    /**
     * Creates new form Clientes
     */
    public Clientes(firebase firebaseInstance) {
        this.firebaseInstance = firebaseInstance;
        this.servicioTecnico = InicioSesion.getServicioTecnico();
        initComponents();
        AgregarCliente menucliente = new AgregarCliente (firebaseInstance,this);
        MostrarPanelCliente(menucliente);
        cargarClientesLocales();
    }

    public void cargarClientesLocales(){
        List<Cliente> clientes = servicioTecnico.getListaClientes();

        Optional.ofNullable(clientes)
                .ifPresentOrElse(
                  lista -> {
                      DefaultTableModel model = (DefaultTableModel)  TablaClientes.getModel();
                      model.setRowCount(0);
                      lista.stream()
                              .map(cliente -> new Object[]{
                                      cliente.getNombre(),
                                      cliente.getApellido(),
                                      cliente.getTelefono(),
                                      cliente.getEmail(),
                                      cliente.getRut(),
                                      cliente.getRegion(),
                                      cliente.getComuna()
                              })
                              .forEach(model ::addRow);
                  },
                        () -> System.out.println("Lista Vacia")
                );
    }

    public void refrescarTabla(){
        cargarClientesLocales();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregarCliente = new javax.swing.JButton();
        PanelCliente = new javax.swing.JPanel();
        BotonEliminarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarCliente.setText("Agregar Cliente");
        BotonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 120, 30));

        javax.swing.GroupLayout PanelClienteLayout = new javax.swing.GroupLayout(PanelCliente);
        PanelCliente.setLayout(PanelClienteLayout);
        PanelClienteLayout.setHorizontalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        PanelClienteLayout.setVerticalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jPanel1.add(PanelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 590));

        BotonEliminarCliente.setText("Eliminar Cliente");
        BotonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 120, 30));

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Telefono","Email","Rut","Region","Comuna"
            }
        ));
        jScrollPane1.setViewportView(TablaClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 520, 320));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {
        AgregarCliente agcli = new AgregarCliente(firebaseInstance, this);
        MostrarPanelCliente(agcli);
    }

    private void BotonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {
        EliminarCliente elicli = new EliminarCliente (firebaseInstance);
        MostrarPanelCliente(elicli);
}

    private javax.swing.JButton BotonAgregarCliente;
    private javax.swing.JButton BotonEliminarCliente;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
}
