/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionClientes;
import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.*;
import org.example.firebase;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author basty
 */
public class Clientes extends javax.swing.JPanel {
    private firebase firebaseInstance;
    private DefaultTableModel modeloTabla;

     private void MostrarPanelCliente(JPanel pag ){
        
        pag.setSize(1500, 590);
        pag.setLocation(0,0);
        
        PanelCliente.removeAll();
        PanelCliente.add(pag, BorderLayout.CENTER);
        PanelCliente.revalidate();
        PanelCliente.repaint(); 
     }



    /**
     * Creates new form Clientes
     */
    public Clientes(firebase firebaseInstance) {
        this.firebaseInstance = firebaseInstance;
        initComponents();
        cargarClientesDesdeFirebase();
        AgregarCliente menucliente = new AgregarCliente (firebaseInstance);
        MostrarPanelCliente(menucliente);

    }

    private void cargarClientesDesdeFirebase(){
        DefaultTableModel modeloTabla = (DefaultTableModel) TablaClientes.getModel();
        modeloTabla.setRowCount(0);

        DefaultTableModel modeloTablaDirecciones = (DefaultTableModel) TablaDireccionClientes.getModel();
        modeloTablaDirecciones.setRowCount(0);



        try{
            Firestore db = firebaseInstance.getFirestore();
            ApiFuture<QuerySnapshot> future = db.collection("Registro De Clientes").get();
            QuerySnapshot querySnapshot = future.get();

            List<String[]> listaClientes = new ArrayList<>();
            List<String[]> listaDirecciones = new ArrayList<>();

            for (QueryDocumentSnapshot document : querySnapshot.getDocuments()) {
                String nombre = document.getString("Nombre");
                String apellido = document.getString("Apellido");
                String telefono = document.getString("Telefono");
                String email = document.getString("Email");
                String rut = document.getString("Rut");
                String region = document.getString("Region");
                String comuna = document.getString("Comuna");
                String calle = document.getString("Calle");
                String numero = document.getString("Numero");

                listaClientes.add(new String[]{nombre, apellido, telefono,email,rut,});
                listaDirecciones.add(new String[]{region, comuna, calle, numero});

            } for (String[] cliente : listaClientes) {
                modeloTabla.addRow(cliente);
            }
            for (String[] direccion : listaDirecciones) {
                modeloTablaDirecciones.addRow(direccion);
            }
        }catch (Exception e){
            e.printStackTrace();
            System.out.println("Error al cargar datos"+ e.getMessage());
        }
    }
    public void refrescarTabla(){
        cargarClientesDesdeFirebase();
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregarCliente = new javax.swing.JButton();
        PanelCliente = new javax.swing.JPanel();
        BotonModificarCliente = new javax.swing.JButton();
        BotonEliminarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDireccionClientes = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarCliente.setText("Agregar Cliente");
        BotonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 120, 30));

        javax.swing.GroupLayout PanelClienteLayout = new javax.swing.GroupLayout(PanelCliente);
        PanelCliente.setLayout(PanelClienteLayout);
        PanelClienteLayout.setHorizontalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        PanelClienteLayout.setVerticalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jPanel1.add(PanelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 590));

        BotonModificarCliente.setText("Modificar Cliente");
        BotonModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 130, 30));

        BotonEliminarCliente.setText("Eliminar Cliente");
        BotonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 430, 120, 30));

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Nombre", "Apellido", "Telefono", "Email", "Rut"
            }
        ));
        jScrollPane1.setViewportView(TablaClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 520, 320));

        TablaDireccionClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Region", "Comuna", "Calle", "Numero"
            }
        ));
        jScrollPane2.setViewportView(TablaDireccionClientes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 440, 320));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarClienteActionPerformed
       cargarClientesDesdeFirebase();
        AgregarCliente agcli = new AgregarCliente(firebaseInstance);
        MostrarPanelCliente(agcli);
        refrescarTabla();
        
    }//GEN-LAST:event_BotonAgregarClienteActionPerformed

    private void BotonModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarClienteActionPerformed
        ModificarCliente modcli = new ModificarCliente();
        MostrarPanelCliente(modcli);
    }//GEN-LAST:event_BotonModificarClienteActionPerformed

    private void BotonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarClienteActionPerformed
        EliminarCliente elicli = new EliminarCliente ();
        MostrarPanelCliente(elicli);
    }//GEN-LAST:event_BotonEliminarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarCliente;
    private javax.swing.JButton BotonEliminarCliente;
    private javax.swing.JButton BotonModificarCliente;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JTable TablaDireccionClientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
