/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.Interfaces.AdministracionClientes;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import org.example.ServicioTecnico;
import org.example.firebase;

import javax.swing.*;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author basty
 */
public class EliminarCliente extends javax.swing.JPanel {
    private Clientes clientes;
    private firebase firebaseInstance;

    /**
     * Creates new form EliminarCliente
     */
    public EliminarCliente(firebase firebaseInstance) {
        this.firebaseInstance = firebaseInstance;
        this.clientes = new Clientes(firebaseInstance);
        initComponents();
    }

    private void eliminarClientePorRut(String rut){
        try{
            Firestore db = firebaseInstance.getFirestore();
            CollectionReference collectionRef = db.collection("Registro De Clientes");
            ApiFuture<QuerySnapshot> query = collectionRef.whereEqualTo("Rut", rut).get();
            QuerySnapshot querySnapshot = query.get();
            System.out.println("consultando clientes con rut"+ rut);

            if(!querySnapshot.isEmpty()){
                for(QueryDocumentSnapshot document : querySnapshot.getDocuments()){
                    document.getReference().delete().get();
                    System.out.println("Cliente con Rut"+ rut +"Eliminado de la firebase");
                }
                JOptionPane.showMessageDialog(null, "Cliente con Rut "+ rut +" eliminado de la firebase");
            }else {
                JOptionPane.showMessageDialog(null, "No hay clientes con Rut "+ rut +" en la firebase");
                System.out.println("No se encontro un cliente con rut"+ rut);
            }
        }catch (InterruptedException| ExecutionException e){
            e.printStackTrace();
            System.err.println("Error durante la operacion"+e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEliminarClientePorRut = new javax.swing.JTextField();
        BtnEliminarCliente = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Aqui se eliminaran los clientes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel2.setText("Ingrese el rut de el cliente que decee eliminar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtEliminarClientePorRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarClientePorRutActionPerformed(evt);
            }
        });
        add(txtEliminarClientePorRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, 30));

        BtnEliminarCliente.setText("Eliminar cliente");
        BtnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarClienteActionPerformed(evt);
            }
        });
        add(BtnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 250, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEliminarClientePorRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarClientePorRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEliminarClientePorRutActionPerformed

    private void BtnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarClienteActionPerformed
         String rut = txtEliminarClientePorRut.getText().trim();
         if(rut.isEmpty()){
             JOptionPane.showMessageDialog(null, "Debe ingresar el rut del cliente");
             return;
         }
         eliminarClientePorRut(rut);
         clientes.refrescarTabla();


    }//GEN-LAST:event_BtnEliminarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtEliminarClientePorRut;
    // End of variables declaration//GEN-END:variables
}
